queue_rules:
  - name: shared_queue
    conditions:
      - "#approved-reviews-by>=1"

      # Must write expected checks explicitly
      # Reference: https://docs.mergify.com/conditions/#validating-all-status-checks
      - check-success=analyze
      - check-success=check_license
      - check-success=golangci_lint
