run:
  go: "1.18"
  deadline: 10m
  concurrency: 8
  build-tags:
    - sparrow

output:
  format: json
  sort-results: true

linters:
  enable:
    - revive
    - staticcheck
# https://github.com/golangci/golangci-lint/issues/2649
#    - structcheck
    - stylecheck
    - unused

issues:
  exclude-rules:
  - path: _test\.go
    linters:
      - errcheck
  - linters:
    - lll
    source: "^//go:generate "
  - linters:
    - staticcheck
    text: "SA9003:"

linter:
  errcheck:
    check-type-assertions: true
    check-blank: true
  lll:
    line-length: 120
    tab-width: 1
  maintidx:
    under: 100
  maligned:
    suggest-new: true
