name: GolangciLint

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  golangci-lint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: golangci_lint

    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40.1
          args: --timeout 10m0s
